// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-astal
// from ../gir-files
// DO NOT EDIT

mod mpris;
pub use self::mpris::Mpris;

mod player;
pub use self::player::Player;

mod enums;
pub use self::enums::Loop;
pub use self::enums::PlaybackStatus;
pub use self::enums::Shuffle;

pub(crate) mod functions;

pub(crate) mod traits {
    pub use super::mpris::MprisExt;
    pub use super::player::PlayerExt;
}
pub(crate) mod builders {
    pub use super::player::PlayerBuilder;
}
