// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir-astal
// from ../../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) ASTAL_CAVA_INPUT_ALSA);
    PRINT_CONSTANT((gint) ASTAL_CAVA_INPUT_FIFO);
    PRINT_CONSTANT((gint) ASTAL_CAVA_INPUT_JACK);
    PRINT_CONSTANT((gint) ASTAL_CAVA_INPUT_OSS);
    PRINT_CONSTANT((gint) ASTAL_CAVA_INPUT_PIPEWIRE);
    PRINT_CONSTANT((gint) ASTAL_CAVA_INPUT_PORTAUDIO);
    PRINT_CONSTANT((gint) ASTAL_CAVA_INPUT_PULSE);
    PRINT_CONSTANT((gint) ASTAL_CAVA_INPUT_SHMEM);
    PRINT_CONSTANT((gint) ASTAL_CAVA_INPUT_SNDIO);
    PRINT_CONSTANT((gint) ASTAL_CAVA_INPUT_WINSCAP);
    return 0;
}
