// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir-astal
// from ../../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalCavaCavaClass", sizeof(AstalCavaCavaClass), alignof(AstalCavaCavaClass));
    printf("%s;%zu;%zu\n", "AstalCavaInput", sizeof(AstalCavaInput), alignof(AstalCavaInput));
    return 0;
}
