[options]
library = "AstalCava"
version = "0.1"
min_cfg_version = "0.1"
target_path = "."
girs_directories = ["../gir-files", "../gir-astal"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true
genereate_builder = true

generate = ["AstalCava.*", "AstalCava.Input"]

manual = []

[[object]]
name = "AstalCava.Cava"
status = "generate"
# fails due to input not implementing Value. use get_default instead
generate_builder = false
manual_traits = ["CavaExtManual"]

[[object.function]]
name = "get_values"
manual = true
