[options]
library = "Astal"
version = "4.0"
min_cfg_version = "4.0"
target_path = "."
girs_directories = ["../gir-files", "../gir-astal"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true
genereate_builder = true

generate = [
    "Astal.WindowAnchor",
    "Astal.Exclusivity",
    "Astal.Layer",
    "Astal.Keymode",
]

manual = [
    "AstalIO.Application",
    "Gtk.Application",
    "Gtk.Accessible",
    "Gtk.Buildable",
    "Gtk.ConstraintTarget",
    "Gtk.Native",
    "Gtk.Widget",
    "Gtk.Root",
    "Gtk.Align",
    "Gtk.Scale",
    "Gtk.Range",
    "Gtk.AccessibleRange",
    "Gtk.ShortcutManager",
    "Gtk.LayoutManager",
    "Gtk.Overflow",
    "Gtk.AccessibleRole",
    "Gtk.Window",
    "Gtk.Box",
    "Gtk.Orientable",
    "Gio.SocketConnection",
    "Gio.ApplicationFlags",
    "Gio.Application",
    "Gio.ActionGroup",
    "Gio.ActionMap",
    "Gio.MenuModel",
    "Gdk.Display",
    "Gdk.Monitor",
    "Gdk.Cursor",
]

[[object]]
name = "Astal.Window"
status = "generate"
generate_builder = true

[[object]]
name = "Astal.Application"
status = "generate"
generate_builder = true


[[object]]
name = "Astal.Box"
status = "generate"
# TODO: generate_builder = true when &[gtk4::Widget] implements Into<Value>
generate_builder = false

[[object]]
name = "Astal.Slider"
status = "generate"
generate_builder = true
