// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-astal
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{translate::*};

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "AstalCavaInput")]
pub enum Input {
    #[doc(alias = "ASTAL_CAVA_INPUT_FIFO")]
    Fifo,
    #[doc(alias = "ASTAL_CAVA_INPUT_PORTAUDIO")]
    Portaudio,
    #[doc(alias = "ASTAL_CAVA_INPUT_PIPEWIRE")]
    Pipewire,
    #[doc(alias = "ASTAL_CAVA_INPUT_ALSA")]
    Alsa,
    #[doc(alias = "ASTAL_CAVA_INPUT_PULSE")]
    Pulse,
    #[doc(alias = "ASTAL_CAVA_INPUT_SNDIO")]
    Sndio,
    #[doc(alias = "ASTAL_CAVA_INPUT_OSS")]
    Oss,
    #[doc(alias = "ASTAL_CAVA_INPUT_JACK")]
    Jack,
    #[doc(alias = "ASTAL_CAVA_INPUT_SHMEM")]
    Shmem,
    #[doc(alias = "ASTAL_CAVA_INPUT_WINSCAP")]
    Winscap,
#[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for Input {
    type GlibType = ffi::AstalCavaInput;

    #[inline]
fn into_glib(self) -> ffi::AstalCavaInput {
match self {
            Self::Fifo => ffi::ASTAL_CAVA_INPUT_FIFO,
            Self::Portaudio => ffi::ASTAL_CAVA_INPUT_PORTAUDIO,
            Self::Pipewire => ffi::ASTAL_CAVA_INPUT_PIPEWIRE,
            Self::Alsa => ffi::ASTAL_CAVA_INPUT_ALSA,
            Self::Pulse => ffi::ASTAL_CAVA_INPUT_PULSE,
            Self::Sndio => ffi::ASTAL_CAVA_INPUT_SNDIO,
            Self::Oss => ffi::ASTAL_CAVA_INPUT_OSS,
            Self::Jack => ffi::ASTAL_CAVA_INPUT_JACK,
            Self::Shmem => ffi::ASTAL_CAVA_INPUT_SHMEM,
            Self::Winscap => ffi::ASTAL_CAVA_INPUT_WINSCAP,
            Self::__Unknown(value) => value,
}
}
}

#[doc(hidden)]
impl FromGlib<ffi::AstalCavaInput> for Input {
    #[inline]
unsafe fn from_glib(value: ffi::AstalCavaInput) -> Self {
        skip_assert_initialized!();
        
match value {
            ffi::ASTAL_CAVA_INPUT_FIFO => Self::Fifo,
            ffi::ASTAL_CAVA_INPUT_PORTAUDIO => Self::Portaudio,
            ffi::ASTAL_CAVA_INPUT_PIPEWIRE => Self::Pipewire,
            ffi::ASTAL_CAVA_INPUT_ALSA => Self::Alsa,
            ffi::ASTAL_CAVA_INPUT_PULSE => Self::Pulse,
            ffi::ASTAL_CAVA_INPUT_SNDIO => Self::Sndio,
            ffi::ASTAL_CAVA_INPUT_OSS => Self::Oss,
            ffi::ASTAL_CAVA_INPUT_JACK => Self::Jack,
            ffi::ASTAL_CAVA_INPUT_SHMEM => Self::Shmem,
            ffi::ASTAL_CAVA_INPUT_WINSCAP => Self::Winscap,
            value => Self::__Unknown(value),
}
}
}

