// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-astal
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,Notifd};
use glib::{translate::*};


#[doc(alias = "astal_notifd_get_default")]
#[doc(alias = "get_default")]
#[allow(clippy::should_implement_trait)]pub fn default() -> Option<Notifd> {
    assert_initialized_main_thread!();
    unsafe {
        from_glib_full(ffi::astal_notifd_get_default())
    }
}
